on:
  push:
    branches:
      - thesis
  pull_request:
    branches:
      - thesis

jobs:
  typecheck:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Typechecking
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v2
      - name: Run Agda
        id: typecheck
        uses: georgejkaye/agda-github-action@v1.0
        with:
          main-file: index.lagda.md
          source-dir: source/TWA/Thesis/
          unsafe: true
      - name: Deploy HTML to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: html
          FOLDER: source/TWA/Thesis/html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
